### ISSUE TITLE
Bluetooth Remote can lockup Zero

### ISSUE THREAD

**Issue by w1wra** [flipperdevices/Flipper-iOS-App#124]
If you use the remote function of the iOS app and turn off Bluetooth,  you need to reboot the Zero.
I think if Bluetooth gets disabled from phone, keys on Zero should still work. 

A left + back reset still works, but all other button combinations seem to have no effect.

**Comment by tonyfreeman** [comment]
Can't reproduce. Feel free to reopen if you still have this issue.
