### ISSUE TITLE
Almost impossible to unlock FlipperZero via iPhone app

### ISSUE THREAD

**Issue by JulyIghor** [flipperdevices/Flipper-iOS-App#129]
Looks like there is dead interval between clicks via mobile app.
It makes very difficult to quickly press back button three times and unlock Flipper.
Most clicks are ignored.

**Comment by tonyfreeman** [comment]
Sorry for the late response. Please use our [forum](https://forum.flipperzero.one/c/mobile/14) to submit an issue or feature request.
