### ISSUE TITLE
Add possibility to update with custom firmware

### ISSUE THREAD

**Issue by xslim** [flipperdevices/Flipper-iOS-App#133]
Is it possible to add a possibility to update Flipper with custom firmware?
If not - a possibility to trigger the update, if the update files are placed manually on SD card?

**Comment by skotopes** [comment]
> Is it possible to add a possibility to update Flipper with custom firmware?
> If not - a possibility to trigger the update, if the update files are placed manually on SD card?

On flipper use archive to open update.fuf and it will start updater.

**Comment by tonyfreeman** [comment]
Sorry for the late response. Please use our [forum](https://forum.flipperzero.one/c/mobile/14) to submit an issue or feature request.
