### ISSUE TITLE
Screen Streaming image interpolation mode

### ISSUE THREAD

**Issue by thebitbrine** [flipperdevices/Flipper-iOS-App#135]
When screen streaming, the image is not sharp.
This might be fixed by changing the interpolation mode to Nearest-neighbor.

**Comment by thebitbrine** [comment]
however, if the image is being created on Flipper and then being sent to iOS instead of sending raw pixel values, this can't be fixed here and the firmware has to be patched :(

**Comment by tonyfreeman** [comment]
Sorry for the late response. Please use our [forum](https://forum.flipperzero.one/c/mobile/14) to submit an issue or feature request.
