### ISSUE TITLE
Multiple Flipper Zeros

### ISSUE THREAD

**Issue by natehome** [flipperdevices/Flipper-iOS-App#138]
Please allow the app to manage multiple Flippers. Maybe have a global file catalog of all the files the app has seen on the flippers you own, and have device specific file catalogs for the individual flippers. That way you could move files easily between flippers and not need multiple iOS devices.

**Comment by tonyfreeman** [comment]
Sorry for the late response. Please use our [forum](https://forum.flipperzero.one/c/mobile/14) to submit an issue or feature request.
