### ISSUE TITLE
Remote Control: Buttons Long Press

### ISSUE THREAD

**Issue by braghetto** [flipperdevices/Flipper-iOS-App#169]
Currently the remote control does not support the use of a long press of the back button. Some applications such as ProtoView (subghz) use back button long press to exit app.
Same as for the Ok button, some applications use a long press on the Ok button for different functions.

Tested on the latest mobile ios app version: 1.6.4

**Comment by tonyfreeman** [comment]
Fixed in upcoming 1.6.6 (348) build
