### ISSUE TITLE
Catalog of apps lagging while scrolling it

### ISSUE THREAD

**Issue by resashkin** [flipperdevices/Flipper-iOS-App#171]
List of app in Hub Catalog of Apps is lagging while scrolling. Screenshots and AppIcons are not cached from the App.

Steps to reproduce:
1. Go to App
2. Go to Hub tab
3. Start scroll list of apps Down -> Requested Images from Network are replacing Placeholders (Scroll is lagging)
4. Start scroll list of apps Up -> Requested Images from Network are replacing Placeholders (Scroll is lagging)

Expected result:
-Image content of needed to be cached, it does not need to request them second time, when user sees it again.

**Comment by tonyfreeman** [comment]
Closed by https://github.com/flipperdevices/Flipper-iOS-App/pull/172
