### ISSUE TITLE
Uploading firmware to Flipper stops randomly

### ISSUE THREAD

**Issue by krupers** [flipperdevices/Flipper-iOS-App#173]
[07_27_00 05-08-2023.txt](https://github.com/flipperdevices/flipperzero-firmware/files/12290105/07_27_00.05-08-2023.txt)
[01_07_32 05-08-2023.txt](https://github.com/flipperdevices/flipperzero-firmware/files/12290106/01_07_32.05-08-2023.txt)
[00_58_17 05-08-2023.txt](https://github.com/flipperdevices/flipperzero-firmware/files/12290107/00_58_17.05-08-2023.txt)
[00_39_12 05-08-2023.txt](https://github.com/flipperdevices/flipperzero-firmware/files/12290109/00_39_12.05-08-2023.txt)
[01_08_25 05-08-2023.txt](https://github.com/flipperdevices/flipperzero-firmware/files/12290110/01_08_25.05-08-2023.txt)
### Describe the bug.

With latest releases update 0.88.0 I am encountering an issue with update. I am using a mobile app and usually it takes 5-10 minutes to update the firmware. With 0.88.0 I am trying to update and it pauses on different moments of percentage progress. I tried to reboot the Flipper OS, the app, abandon Sync, and it always stops at random progress. 

### Reproduction

1. Reboot the Flipper OS
2. Start the Flipper app (iOS)
3. Wait for Flipper to be connected and synced
4. Click on update button to upgrade from 0.87.0 to 0.88.0

### Target

Flipper zero update

### Anything else?

Tried this multiple times and maximum progress bar reached was 43%

**Comment by krupers** [comment]
Okay, I have found a solution, I think. I have noticed that after previous update my PIN disappeared and I was forced to create new one again. Then I charged flipper battery and then everything was okay. Now I have latest firmware. But this is strange.

**Comment by doomwastaken** [comment]
Could you provide version of iOS app, so we could try and reproduce it? We've tested with latest iOS app during release

**Comment by krupers** [comment]
Sure, my phone is iPhone 14 Pro Max (iOS 16.6) with installed latest Flipper App (v1.6.4).
Always when I am having an old App it automatically notices me about the update.

**Comment by doomwastaken** [comment]
Alright, thank you for details. We will try to experiment   with locking the device

**Comment by skotopes** [comment]
Next time you see this issue please try changing Settings->System->Sleep Method to legacy

**Comment by krupers** [comment]
Hey, thank you for the tip. Unfortunately I already have this mode enabled, because of that Core error we all having last time :( So this mode is not helping. Maybe should I disable it then?

**Comment by skotopes** [comment]
@krupers some logs from the device will help

**Comment by krupers** [comment]
@skotopes All the logs from the moment I have tried to update were attached to the first post. I hope they will help

**Comment by skotopes** [comment]
Logs says that data was transferred till the last moment before disconnect.
Let's move this issue to appropriate github repo for further debug.

**Comment by skotopes** [comment]
@tonyfreeman can you take a look?

**Comment by tonyfreeman** [comment]
Can't see anything useful, it just loses connection for some reason. 
@krupers have you faced this issue since? We need debug logs from device.

**Comment by tonyfreeman** [comment]
This might be related to the UI issue when an update is happening but the progress bar is not responsive. Should be fixed in latest testflight release. Feel free to reopen if it's not.
