### ISSUE TITLE
Custom firmware shows as official firmware "Dev" channel

### ISSUE THREAD

**Issue by WillyJL** [flipperdevices/Flipper-iOS-App#174]
With the current `channel` detection from `softwareRevision` logic, there is no way to make custom firmware be shown as custom firmware in the overview menu. It will show as `Dev <commit>` just like official firmware dev branch does, just that it makes no sense for that to happen on custom firmware and would lead to confusing users.

The problematic code is here:
https://github.com/flipperdevices/Flipper-iOS-App/blob/de05ae402270a6d44d85fe1bd9b3ac0c52381267/Flipper/Packages/Core/Sources/Flipper/InstalledFirmware.swift#L21-L38

I can't think of a solution for this based off of just the `softwareRevision` that would not break official firmware version description. HOWEVER: the Android app shows the correct information *always*. It is veeery confusing how the 2 apps show different info. Perhaps instead of erroneously using `softwareRevision`, use the actual version string provided by the device? Just a thought...

**Comment by tonyfreeman** [comment]
Fixed in 1.6.5

**Comment by WillyJL** [comment]
Thanks!
