### ISSUE TITLE
Incorrect display of app update count label

### ISSUE THREAD

**Issue by valentineus** [flipperdevices/Flipper-iOS-App#175]
**Steps to reproduce**:
1. Open the application.
2. Navigate to the Hub tab.
3. Open the Apps section.

**Expected behavior**:
The label should correctly display the number of apps that require an update (e.g., "10").

**Actual behavior**:
The label incorrectly displays the number of apps for update if there are more than 9.

**Additional information**:
- Phone model: iPhone 13 (MLA23LL/A)
- OS version: 16.6
- App version: 1.6.5

**Screenshots/video**:
<img width="331" alt="Screenshot 2023-09-02 at 23 29 41" src="https://github.com/flipperdevices/Flipper-iOS-App/assets/24860049/1889f2c9-7769-4445-aa4c-56ba1684d6c3">

**Comment by tonyfreeman** [comment]
Fixed, thanks!

**Comment by valentineus** [comment]
Awesome, thanks a lot! 🚀
