### ISSUE TITLE
Unable to add apps via hub

### ISSUE THREAD

**Issue by asutermo** [flipperdevices/Flipper-iOS-App#215]
I'll post to forum too. No dice on discord.

I am unable to add apps when I'm connected to the flipper on ios. If I'm unconnected I can click the buttons but I cannot otherwise.

I've tried 2.4 ghz/5 ghz bands.
I've tried 5G and LTE
I've restarted and reinstalled.
No effect.

I'll add any info as needed

**Comment by tonyfreeman** [comment]
Should be fixed in the latest release. Feel free to reopen if you're still facing this issue
