### ISSUE TITLE
Flipper app forces update even if at latest version

### ISSUE THREAD

**Issue by robot-penguin34** [flipperdevices/Flipper-iOS-App#220]
When connecting a new flipper, the mobile app will show that the device isn't updated and will show a green update button even if the flipper is up to date. (Note: I am using latest version on both sides)

How to replicate:
1. Unpair your flipper, or delete the app 
2. Re-connect it
3. There should now be a green update button. 
Edit: 4. Delete example badusb scripts

Thank you for your time, and constant work to improve this tool for everyone.

**Comment by tonyfreeman** [comment]
Please attach a screenshot here

**Comment by robot-penguin34** [comment]
Sorry, meant to close this. It was caused by an issue with fetching geo location. (Now fixed). I think it was issue #222 that fixed the problem.
