### ISSUE TITLE
Inhibit sleep, or allow background operation, while doing an "Update All" from the hub

### ISSUE THREAD

**Issue by kbembedded** [flipperdevices/Flipper-iOS-App#230]
Forgive me as I do not know all of the correct terms for iOS operations.

When doing a firmware update over Bluetooth, this seems to get backgrounded in a way that if the iDevice locks, the firmware upload operation over Bluetooth still happens in the background, and if the iDevice is not intentionally locked then the upload process keeps the iDevice unlocked and operating.

The same does not happen when updating Flipper apps through the Hub in the mobile app. One has to keep poking the screen to keep the iDevice awake while the updates occur.

Would it be possible to have the same sleep inhibit / backrounding occur during a batch app update?

**Comment by tonyfreeman** [comment]
Yeah, this already fixed in the testflight build https://testflight.apple.com/join/oLyR7YeT
